spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: API@.00.00
    url: jdbc:mysql://219.135.173.91:3306/linai?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
